### ISSUE TITLE
Linhas duplicadas e outros erros encontratos

### ISSUE THREAD

**Issue by pablorenato1** [FelipeSantanaC/Turismo-Irrestrito#13]
* Depois da alteração do sobre, o botão que era usado para testar não esta mais funcionando, então é preciso remover esta parte do código, ela esta gerando erro durante a execução no console do site.
https://github.com/FelipeSantanaC/Turismo-Irrestrito/blob/24f4ca35ba2947bdfb8eaa6417439aced385183f/authRst/myapp/static/js/app.js#L1-L41

* Também vi erros referentes a esta linha, porém não explorei (Acontece quando abre o pop up de Login)
https://github.com/FelipeSantanaC/Turismo-Irrestrito/blob/24f4ca35ba2947bdfb8eaa6417439aced385183f/authRst/myapp/static/js/app.js#L72

* Também há este problema com as tags não tendo um id único, podendo ser adicionado o tipo dela também como id, só para ter uma diferenciação e não apresentar este erro novamente.
![image](https://github.com/FelipeSantanaC/Turismo-Irrestrito/assets/56098864/cfa9c5ba-ca66-44e1-ad37-0f4dbaaa7f63)

* De forma recorrente eu vejo erro referente a esta função, talvez deixa-lá dentro da função (A primeira) que só vai rodar quando a página for carregada totalmente.
https://github.com/FelipeSantanaC/Turismo-Irrestrito/blob/24f4ca35ba2947bdfb8eaa6417439aced385183f/authRst/myapp/static/js/app.js#L183

* O header da tela de sobre e de Perfil estão diferentes das demais, estão mais proximos da borda.
Tela de Perfil:
![image](https://github.com/FelipeSantanaC/Turismo-Irrestrito/assets/56098864/b89866e7-1da6-4f41-9695-70a9c7ca3aff)
Tela Inicial (home)
![image](https://github.com/FelipeSantanaC/Turismo-Irrestrito/assets/56098864/d83cede5-e7af-41eb-9bcf-db21a2b66acc)

**Comment by manuferreira** [comment]
You criar uma task sobre isso lá no Trello. Valeu :slightly_smiling_face:
